baseURL = "https://pauloportugal.github.io"
languageCode = "en-gb"
title = "Paulo Monteiro"
enableGitInfo = false
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false

# Pagination settings
[pagination]
  pagerSize = 5

# Make sure to include JSON output to support the search functionality
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Import the theme as a Hugo Module
[module]
  [[module.imports]]
    path = "github.com/geekifan/hugo-theme-chirpy"
